// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Code struct {
	ID        int64          `json:"id"`
	RoomID    int64          `json:"room_id"`
	Content   sql.NullString `json:"content"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type Message struct {
	ID        int64          `json:"id"`
	RoomID    sql.NullInt64  `json:"room_id"`
	Content   sql.NullString `json:"content"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Profile struct {
	ID        int64        `json:"id"`
	Username  string       `json:"username"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	AvatarUrl []byte       `json:"avatar_url"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Room struct {
	ID        int64         `json:"id"`
	OwnerID   sql.NullInt64 `json:"owner_id"`
	MemberID  []int64       `json:"member_id"`
	CreatedAt sql.NullTime  `json:"created_at"`
	UpdatedAt sql.NullTime  `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}
